@RecordCollection_HostAddress = http://localhost:5093

GET {{RecordCollection_HostAddress}}/api/recordcollection
Accept: application/json

###

GET {{RecordCollection_HostAddress}}/api/recordcollection/3
Accept: application/json

###

POST {{RecordCollection_HostAddress}}/api/recordcollection
Content-Type: application/json

{
    "artistName" : "The Wallflowers",
    "albumTitle" : "Bringing Down the Horse",
    "releaseYear" : 1996,
    "discogsId" : 927532321
}

###

DELETE {{RecordCollection_HostAddress}}/api/recordcollection/4

###

PUT {{RecordCollection_HostAddress}}/api/recordcollection/4
Content-Type: application/json

{
    "artistName" : "Counting Crows",
    "albumTitle" : "August and Everything After",
    "releaseYear" : 1993,
    "discogsId" : 921254321
}